### ISSUE TITLE
Swapping car Desync Issue

### ISSUE THREAD

**Issue by adweex** [qbcore-framework/qb-vehicleshop#159]
I've seen issues been deleted. So the bug still exists. If you swap modded / addon cars sometimes it will desync.
Menu header will be the previous car, but the choosen car will be spawned. Once the player buys his car, the person will get he car that is shown in the menu header.

**Comment by FrogCF** [comment]
We have same problem above ^^

**Comment by adweex** [comment]
> 

It is a problem since vehicleshop 2.0 was released. Sadly no fix yet :/ I tried to fix it but a rework would be better. I tested it again, it happens with the basic gta cars as well sadly.

**Comment by GhzGarage** [comment]
It’s nothing to do with the script, the menu returns before the model is loaded. Literally just close menu, walk away and then back or modify the code so it waits longer

**Comment by adweex** [comment]
> It’s nothing to do with the script, the menu returns before the model is loaded. Literally just close menu, walk away and then back or modify the code so it waits longer

In client main line 574 the code waits until the model is loaded. I even implemented a similiar code to double check that the model is loaded and the car is spawned as well before sending the data to the menu however still produces the same issue. It is a huge bug for servers that uses qb-vehicleshop because players buying the cars by the visual feedback provided by the script.

I'll try to find a solution to the problem then PR it.

**Comment by adweex** [comment]
This seems solved the issue but still waiting for our testers to validate the fix. Not much changed however try if you would like. Tests will be completed in 24-48 hours. Also I've fixed the issue that menu does not close upon leaving the polyzone.
```
RegisterNetEvent('qb-vehicleshop:client:swapVehicle', function(data)
    local shopName = data.ClosestShop
    if Config.Shops[shopName]["ShowroomVehicles"][data.ClosestVehicle].chosenVehicle ~= data.toVehicle then
        local closestVehicle, closestDistance = QBCore.Functions.GetClosestVehicle(vector3(Config.Shops[shopName]["ShowroomVehicles"][data.ClosestVehicle].coords.x, Config.Shops[shopName]["ShowroomVehicles"][data.ClosestVehicle].coords.y, Config.Shops[shopName]["ShowroomVehicles"][data.ClosestVehicle].coords.z))
        if closestVehicle == 0 then return end
        if closestDistance < 5 then QBCore.Functions.DeleteVehicle(closestVehicle) end
        while DoesEntityExist(closestVehicle) do
            Wait(250)
        end
        Config.Shops[shopName]["ShowroomVehicles"][data.ClosestVehicle].chosenVehicle = data.toVehicle -- ide meg berakva
        local model = GetHashKey(data.toVehicle)
        RequestModel(model)
        while not HasModelLoaded(model) do
            Citizen.Wait(250)
        end
        local veh = CreateVehicle(model, Config.Shops[shopName]["ShowroomVehicles"][data.ClosestVehicle].coords.x, Config.Shops[shopName]["ShowroomVehicles"][data.ClosestVehicle].coords.y, Config.Shops[shopName]["ShowroomVehicles"][data.ClosestVehicle].coords.z, false, false)
        while not DoesEntityExist(veh) do
            Citizen.Wait(250)
        end
        SetModelAsNoLongerNeeded(model)        
        SetVehicleOnGroundProperly(veh)
        SetEntityInvincible(veh,true)
        SetEntityHeading(veh, Config.Shops[shopName]["ShowroomVehicles"][data.ClosestVehicle].coords.w)
        SetVehicleDoorsLocked(veh, 3)
        FreezeEntityPosition(veh, true)
        SetVehicleNumberPlateText(veh, 'BUY ME') 
    end
end)
```

**Comment by GhzGarage** [comment]
The code you added here should fix it

        while not DoesEntityExist(veh) do
            Citizen.Wait(250)
        end

**Comment by adweex** [comment]
> The code you added here should fix it
> 
> ```
>     while not DoesEntityExist(veh) do
>         Citizen.Wait(250)
>     end
> ```

At first I thought that as well. However during testing It failed sadly because the script were still getting the data of the previous car causing the issue. However It seems the code above fixed it. I'll sending a PR soon, tests outcome shows positive results even on low end PCs.

**Comment by adweex** [comment]
> We have same problem above ^^

Check it if it fixes for you as well!
https://github.com/qbcore-framework/qb-vehicleshop/pull/163
