### ISSUE TITLE
[BUG] Player Managed vehicle shops do not allow to open menu!

### ISSUE THREAD

**Issue by FizzGamingJR** [qbcore-framework/qb-vehicleshop#189]
**Describe the bug**
Upon walking up to a showroom vehicle, once you click the Vehicle Options button it does nothing.

**To Reproduce**
1. Go to a player managed vehicle shop.
2. Get the correct job
3. Try to open the vehicle purchasing menu next to a Showroom Vehicle.

**Expected behavior**
Menu to open with necessary options to sell vehicles.

**Screenshots**
![image](https://user-images.githubusercontent.com/28313136/170061288-8e66a28d-5dc0-4d80-8344-30b47a19b5b1.png)

![image](https://user-images.githubusercontent.com/28313136/170061344-dd9b1a76-b0b9-45de-a1b4-f82c97f7b22b.png)

**Questions (please complete the following information):**
 - When you last updated: 4 Days Ago
 - Are you using custom resource? which ones? N/A
 - Have you renamed `qb-` to something custom? No

**Additional context**
free-use Vehicle Shops work perfectly fine, but player Managed ones have this issue.

**Comment by Molicheu** [comment]
On my freshly updated server, I had no problem with the menu opening for me, I also assume by the looks of it that you're trying to open the menu next to an add-on/replacement car. Try opening the menu next to a vanilla GTA car to see if your custom vehicle was the issue. Might have to change some things around in vehicles.lua for that vehicle. Here is the clip of me proving there is not an issue with the menu https://streamable.com/0lkg7y

**Comment by FizzGamingJR** [comment]
I ended up getting this to work by using admin powers to spawn and load in the custom cars.
Everything is working as expected now and I appreciate your helpful reply :)

**Comment by Nadunnissanka** [comment]
The same issue is with me. For Vanilla Cars as well. Soon as you changed vehicle locations everything stops working. restarting the script "ensure qb-vehicleshop" fixes it but it is a temporary solution. The problem is occurring when trying to have a new vehicle shop.

**Comment by LightUpFam** [comment]
been battling this issue for some time as well. sometimes the script works fine after restarting the resource.  but after a server reset its almost always bugged. Ive taken out cars that were bugged but still it happens.   
besides it not showing the list sometimes , it often gets stuck showing a previous vehicles price and details even though your on a totally different vehicle. ...  I fine myself have to check on the luxury show often.

**Comment by LightUpFam** [comment]
Thought it was solved.  I've removed tons a cars that shouldn't be an issue. 

On a server restart..  luxury does not show the list. 
I have to restart the resource 3-4 times. And then Magicly the menu works.  This is only a problem for luxury. 

I don't want to use a catalog style dealership but I may have to switch.  My citizens complain about this omtlo often. ...
.

You have people saying there's an issue but the response is no there no issue it works fine.

**Comment by ggoodell2** [comment]
> been battling this issue for some time as well. sometimes the script works fine after restarting the resource. but after a server reset its almost always bugged. Ive taken out cars that were bugged but still it happens. besides it not showing the list sometimes , it often gets stuck showing a previous vehicles price and details even though your on a totally different vehicle. ... I fine myself have to check on the luxury show often.

im also having this exact issue but not with just luxury. it does it with pdm as well.

**Comment by ggoodell2** [comment]
so i somehow fixed the needing to restart the resource everytime the server restarted but it still shows a different vehicle name and price when selecting vehicles. it only does it with addon vehicles. gta vanilla vehicles work fine.

**Comment by ggoodell2** [comment]
picture for reference. should say f15084 $1000. https://gyazo.com/6d5b1f2bb5595d3b3b239b9dab5a32cd

**Comment by FizzGamingJR** [comment]
> Thought it was solved. I've removed tons a cars that shouldn't be an issue.
> 
> On a server restart.. luxury does not show the list. I have to restart the resource 3-4 times. And then Magicly the menu works. This is only a problem for luxury.
> 
> I don't want to use a catalog style dealership but I may have to switch. My citizens complain about this too often. ... .
> 
> You have people saying there's an issue but the response is no there no issue it works fine.

Still having all these issues, and I don't want to switch similar to what your saying.
I am tryna dev a server and am on a tight time schedule for doing so, and if this isn't fixed for when I launch my server then am going to have people complaining as well.
There has been issues regarding cars showing, menus showing, or nothing showing since I last developed a server about 2-3 months back and by the looks of it, it's only been fixed in the minor context.

**Comment by FizzGamingJR** [comment]
> so i somehow fixed the needing to restart the resource everytime the server restarted but it still shows a different vehicle name and price when selecting vehicles. it only does it with addon vehicles. gta vanilla vehicles work fine.

I had this issue once, I swapped the vehicle in the menu and restarted the server and everything was back to normal.
Seems like there are major issues with this script atm and idek if they will end up getting fixed considering most of these issues have been here for months.

**Comment by GhzGarage** [comment]
Closing due to OP issue resolved
