### ISSUE TITLE
[BUG] insideShop Nil Check

### ISSUE THREAD

**Issue by wessleym** [qbcore-framework/qb-vehicleshop#270]
**Describe the bug**
After test driving a vehicle and being returned the dealership, I get an error in the F8 console:
SCRIPT ERROR: @qb-vehicleshop/client.lua:181: attempt to index a nil value (field '?')

**To Reproduce**
1. Test drive a car at PDM.
2. Wait for test drive time to complete.
3. Observe the F8 console.

**Expected behavior**
I would expect no Lua errors.

**Screenshots**
N/A

**Questions (please complete the following information):**
 - When you last updated: Maybe three weeks ago
 - Are you using custom resource? which ones? No
 - Have you renamed `qb-` to something custom? No

**Additional context**
In my specific case, `insideShop` gets set to null here:
https://github.com/qbcore-framework/qb-vehicleshop/blob/14baf13203cad92afc0fe7ab6f2c32d6e53a0e41/client.lua#L272

I would recommend a nil check on this line since Lua is trying to retrieve a value from `Config.Shops` with a key `insideShop` of nil:
https://github.com/qbcore-framework/qb-vehicleshop/blob/14baf13203cad92afc0fe7ab6f2c32d6e53a0e41/client.lua#L181

This is my recommended replacement for the above line:
`                if PlayerData and PlayerData.job and insideShop ~= nil and (PlayerData.job.name == Config.Shops[insideShop]['Job'] or Config.Shops[insideShop]['Job'] == 'none') then`

**Comment by xxUnknown13xx** [comment]
> **Describe the bug** After test driving a vehicle and being returned the dealership, I get an error in the F8 console: SCRIPT ERROR: @qb-vehicleshop/client.lua:181: attempt to index a nil value (field '?')
> 
> **To Reproduce**
> 
> 1. Test drive a car at PDM.
> 2. Wait for test drive time to complete.
> 3. Observe the F8 console.
> 
> **Expected behavior** I would expect no Lua errors.
> 
> **Screenshots** N/A
> 
> **Questions (please complete the following information):**
> 
> * When you last updated: Maybe three weeks ago
> * Are you using custom resource? which ones? No
> * Have you renamed `qb-` to something custom? No
> 
> **Additional context** In my specific case, `insideShop` gets set to null here:
> 
> https://github.com/qbcore-framework/qb-vehicleshop/blob/14baf13203cad92afc0fe7ab6f2c32d6e53a0e41/client.lua#L272
> 
> I would recommend a nil check on this line since Lua is trying to retrieve a value from `Config.Shops` with a key `insideShop` of nil:
> 
> https://github.com/qbcore-framework/qb-vehicleshop/blob/14baf13203cad92afc0fe7ab6f2c32d6e53a0e41/client.lua#L181
> 
> This is my recommended replacement for the above line: ` if PlayerData and PlayerData.job and insideShop ~= nil and (PlayerData.job.name == Config.Shops[insideShop]['Job'] or Config.Shops[insideShop]['Job'] == 'none') then`

![qbcvs](https://user-images.githubusercontent.com/113321753/204410600-4230af74-c855-420e-9c1c-4d0d1316d0ea.PNG)
I get the same issue....

**Comment by Z3rio** [comment]
Resolved.

**Comment by wessleym** [comment]
@Z3rio, in the latest commit, line 272 still sets `insideShop` to `nil`, and line 181 still doesn't have a `nil` check.  I don't think this is actually resolved.  Thank you for your work.

**Comment by Z3rio** [comment]
> @Z3rio, in the latest commit, line 272 still sets `insideShop` to `nil`, and line 181 still doesn't have a `nil` check. I don't think this is actually resolved. Thank you for your work.

Hm weird, one of the developers told me to close this so I'm not necessarily the one that checked this.
But I could take a look at it.

**Comment by SlimChances** [comment]
i have this same issue. i applied the above recommended but when trying to buy planes it breaks the script for everyone until after server restart. cars work fine until then.
